/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservation.software;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 11rit
 */
public class search extends javax.swing.JFrame {

    /**
     * Creates new form search
     */
    public search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fromCB = new javax.swing.JComboBox<>();
        toCB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        dateTB = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        avTAB = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bookTB = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("FROM :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 72, 180, -1));

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("TO :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 141, 160, -1));

        fromCB.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        fromCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lal Bahadur Shastri International Airport", "Indira Gandhi International Airport", "Rajiv Gandhi International Airport" }));
        fromCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromCBActionPerformed(evt);
            }
        });
        getContentPane().add(fromCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 450, -1));

        toCB.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        toCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lal Bahadur Shastri International Airport", "Indira Gandhi International Airport", "Rajiv Gandhi International Airport" }));
        toCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCBActionPerformed(evt);
            }
        });
        getContentPane().add(toCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 450, -1));

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("DATE :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 16, 180, -1));
        getContentPane().add(dateTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 129, -1));

        searchBtn.setBackground(new java.awt.Color(255, 255, 204));
        searchBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        searchBtn.setText("SEARCH");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 270, -1));

        avTAB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        avTAB.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        avTAB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PLANE ID", "FROM", "DEPARTURE", "TO", "ARRIVAL", "DATE", "PRICE", "SEAT LEFT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(avTAB);
        if (avTAB.getColumnModel().getColumnCount() > 0) {
            avTAB.getColumnModel().getColumn(0).setMaxWidth(100);
            avTAB.getColumnModel().getColumn(1).setMinWidth(210);
            avTAB.getColumnModel().getColumn(2).setPreferredWidth(7);
            avTAB.getColumnModel().getColumn(3).setMinWidth(210);
            avTAB.getColumnModel().getColumn(4).setPreferredWidth(7);
            avTAB.getColumnModel().getColumn(6).setMaxWidth(100);
            avTAB.getColumnModel().getColumn(7).setMaxWidth(120);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 1160, 150));

        jLabel4.setFont(new java.awt.Font("Footlight MT Light", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("AVAILABLE FLIGHT ARE :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 280, -1));

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("BOOK PLANE ID :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 620, 240, -1));

        bookTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTBActionPerformed(evt);
            }
        });
        getContentPane().add(bookTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, 201, -1));

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jButton2.setText("BOOK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 680, 250, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 250, -1));

        jLabel6.setFont(new java.awt.Font("Footlight MT Light", 1, 20)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\ritik\\VIT\\sem 2\\DBMS\\project\\directly-above-shot-of-figurine-airplane-against-blue-background-EYF04804.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fromCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromCBActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String from = (String) fromCB.getSelectedItem();
        String to = (String) toCB.getSelectedItem();
        String date = dateTB.getText();
        DefaultTableModel tMOdel = (DefaultTableModel) avTAB.getModel();
        tMOdel.setRowCount(0);
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            System.out.println("driver loaded");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","kholo");
            Statement stmt =con.createStatement();
            String query1="select S.PLANE_ID,S.FROM_AIRPORT_ID,S.TO_AIRPORT_ID,S.DEPARTURE_TIME,S.ARRIVAL_TIME,S.SCHEDULE_ID,R.seat_left from schedule S,reservation R where from_airport_id =(select airport_id from airport where airport_name='"+from+"') and to_airport_id =(select airport_id from airport where airport_name='"+to+"') and R.schedule_id=S.schedule_id ";
            ResultSet rs = stmt.executeQuery(query1);
            System.out.println("query executed");
            int count=0;
            while (rs.next()){
                count++;
                DefaultTableModel model = (DefaultTableModel) avTAB.getModel();
                model.addRow(new Object[]{ rs.getInt(1),from,rs.getString(4),to,rs.getString(5),date,7000-50*rs.getInt(7),rs.getInt(7)});
            }
            
        }
        catch(ClassNotFoundException e){
            System.out.println("Driver not loaded");
        }
        catch(NumberFormatException e){
            System.out.println("number not found exception");
        }
        catch(SQLException e){
            System.out.println("query not executed");
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void toCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toCBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            NewJFrame home= new NewJFrame();
            home.show();
            dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String from = (String) fromCB.getSelectedItem();
        String to = (String) toCB.getSelectedItem();
        int book = Integer.parseInt(bookTB.getText());
        int n=20;
        int id =0;
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            System.out.println("driver loaded");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","kholo");
            Statement stmt =con.createStatement();
            String query1="select S.SCHEDULE_ID,R.seat_left from schedule S,reservation R where from_airport_id =(select airport_id from airport where airport_name='"+from+"') and to_airport_id =(select airport_id from airport where airport_name='"+to+"') and R.schedule_id=S.schedule_id and S.plane_id="+book ;
            ResultSet rs = stmt.executeQuery(query1);
            System.out.println("query executed");
            int count=0;
            while (rs.next()){
                count++;
                id=rs.getInt(1);
                n=rs.getInt(2);
            }
            int fin=n-1;
            String query="Update reservation set seat_left="+fin+" where schedule_id="+id ;
            ResultSet qs = stmt.executeQuery(query);
            
        }
        catch(ClassNotFoundException e){
            System.out.println("Driver not loaded");
        }
        catch(NumberFormatException e){
            System.out.println("number not found exception");
        }
        catch(SQLException e){
            System.out.println("query not executed");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bookTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookTBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable avTAB;
    private javax.swing.JTextField bookTB;
    private javax.swing.JTextField dateTB;
    private javax.swing.JComboBox<String> fromCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox<String> toCB;
    // End of variables declaration//GEN-END:variables
}
